repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-xml
    - id: check-merge-conflict
    - id: mixed-line-ending
    - id: end-of-file-fixer
    - id: trailing-whitespace
# autopep8 for Python formatting
- repo: https://github.com/hhatto/autopep8
  rev: v2.1.0
  hooks:
    - id: autopep8
      args: [--recursive --diff --aggressive --aggressive --exit-code --ignore E402 --max-line-length 120 .]
# isort for python imports
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
